### ISSUE TITLE
Timeout Issue

### ISSUE THREAD

**Issue by sehgalvibhor** [Jefferson-Henrique/GetOldTweets#8]
Is there a limit on max tweets that we can get ?
Shows this error on getting 7000 tweets 

java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at sun.security.ssl.InputRecord.readFully(Unknown Source)
        at sun.security.ssl.InputRecord.read(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
        at sun.security.ssl.AppInputStream.read(Unknown Source)
        at java.io.BufferedInputStream.fill(Unknown Source)
        at java.io.BufferedInputStream.read1(Unknown Source)
        at java.io.BufferedInputStream.read(Unknown Source)
        at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
        at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)

**Comment by Jefferson-Henrique** [comment]
Hello, I have already downloaded more than 200k, but that was some time ago. Can you paste here your code, so I can try the same search as you?

**Comment by sehgalvibhor** [comment]
It's actually weird, I tried running it on different system, It runs properly. Any idea why this strange outcomes?

**Comment by Jefferson-Henrique** [comment]
It is quite weird, I have heard some similar cases, which trying on other computers get things right. Sadly I couldn't reproduce the error to investigate deeply.

**Comment by Jefferson-Henrique** [comment]
Can you try again on the newest version?
